AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Budget of $10 per month with notifications for actual and forecasted alerts.

Parameters:
  BudgetLimit:
    Type: Number
    Default: 10
    Description: Monthly budget limit in USD.
  NotificationEmail:
    Type: String
    Description: Email address to send alerts to.

Resources:
  MonthlyBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: MonthlyBudgetLimit
        BudgetLimit:
          Amount: !Ref BudgetLimit
          Unit: USD
        BudgetType: COST
        TimeUnit: MONTHLY
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - Address: !Ref NotificationEmail
              SubscriptionType: EMAIL
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - Address: !Ref NotificationEmail
              SubscriptionType: EMAIL
