AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an ECR repository'

Parameters:
  RepositoryName:
    Type: String
    Description: The name of the ECR repository to create.

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryArn:
    Description: The ARN of the ECR repository
    Value: !GetAtt ECRRepository.Arn
    Export:
      Name: !Sub "${AWS::StackName}-RepositoryArn"
  RepositoryUri:
    Description: The URI of the ECR repository
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}"
    Export:
      Name: !Sub "${AWS::StackName}-RepositoryUri"
