AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Organizations structure including a NonProduction OU and an application-dev account.

Parameters:
  ParentId:
    Type: String
    Description: The ID of the parent root or OU where the NonProduction OU will be created.
  SharedServicesAccountEmail:
    Type: String
    Default: tran.minh.phuong.anh+awsshared@gmail.com
    Description: The email address for the shared-services account. This must be a unique email not associated with another AWS account.
  ApplicationDevAccountEmail:
    Type: String
    Default: tran.minh.phuong.anh+awsappdev@gmail.com
    Description: The email address for the application-dev account. This must be a unique email not associated with another AWS account.

Resources:
  NonProductionOU:
    Type: AWS::Organizations::OrganizationalUnit
    Properties:
      Name: NonProduction
      ParentId: !Ref ParentId

  SharedServicesAccount:
    Type: AWS::Organizations::Account
    Properties:
      AccountName: shared-services
      Email: !Ref SharedServicesAccountEmail
      ParentIds:
        - !Ref ParentId

  ApplicationDevAccount:
    Type: AWS::Organizations::Account
    Properties:
      AccountName: application-dev
      Email: !Ref ApplicationDevAccountEmail
      ParentIds: 
        - !Ref NonProductionOU

Outputs:
  NonProductionOUId:
    Description: The ID of the NonProduction Organizational Unit.
    Value: !Ref NonProductionOU
  ApplicationDevAccountId:
    Description: The ID of the application-dev account.
    Value: !Ref ApplicationDevAccount
  SharedServicesAccountId:
    Description: The ID of the shared-services account.
    Value: !Ref SharedServicesAccount
